setwd("C:/Users/Alice/Documents/Postdoc Freiburg/syllogism64/analysis")
library(RCurl)
library(bitops)
library(metafor)
library(Formula)
sylmeta <- read.csv("C:/Users/Alice/Documents/Postdoc Freiburg/syllogism64/analysis/syllo64metaS.csv")
sylHit <-subset(sylmeta, PointEst == "Hit")
sylCR <-subset(sylmeta, PointEst == "CorrectReject")
sylDet <-subset(sylmeta, PointEst == "Detect")
resHit <- rma(sylHit$yi, sylHit$vi, data = sylHit, slab = paste(Theory))
resHit <- rma(sylHit$yi, sylHit$vi, data = sylHit, method = "HE", slab = paste(Theory))
summary(resHit)
funnel(resHit, main = "Mixed-Effects Model")
forest(resHit)

resCR <- rma(sylCR$yi, sylCR$vi, data = sylCR, slab = paste(Theory))
summary(resCR)
funnel(resCR, main = "Mixed-Effects Model")
forest(resCR)
confint(resCR)

resDet <- rma(sylDet$yi, sylDet$vi, data = sylDet, slab = paste(Theory))
funnel(resDet, main = "Mixed-Effects Model")
forest(resDet)
confint(resDet)